Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1810"
  config.vm.box_check_update = false
  config.vm.network :forwarded_port, guest: 3306, host: 3307
  config.vm.provision :shell, :path => "install.sh"
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.network "private_network", ip: "10.19.17.12"
  config.vm.hostname = "VirtualMachine"
end
